language: cpp
dist: trusty
sudo: required
notifications:
  email: false
git:
  submodules: true
  depth: 3

matrix:
  include:
  - os: linux
    compiler: gcc
    env: release=CamomileLinux64
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev python-dev libfreetype6-dev libgtk-3-dev libcurl4-gnutls-dev alsa libasound2-dev
    - sudo add-apt-repository -y ppa:webkit-team/ppa
    - sudo apt-get -qq update
    - sudo apt-get install -y libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
    script:
    - mkdir Dependencies/LibPd/build && mkdir Dependencies/LibPd/build/makefile/ && cd Dependencies/LibPd/build/makefile
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - cd ../../../..
    - make -C Dependencies/LibPd/build/makefile libpdstatic
    - make -C Instrument/Builds/LinuxMakefile TARGET_ARCH=-m64 CONFIG=Release
    - make -C Effect/Builds/LinuxMakefile TARGET_ARCH=-m64 CONFIG=Release
    - make -C Instrument/Builds/LinuxMakefile-LV2 TARGET_ARCH=-m64 CONFIG=Release
    - make -C Effect/Builds/LinuxMakefile-LV2 TARGET_ARCH=-m64 CONFIG=Release
    before_deploy:
    - rm Plugins/Camomile.a
    - rm Plugins/CamomileFx.a
    - rm Plugins/Examples/camomile.sh
    - cp README.md Plugins/README.md
    - cp ChangeLog.md Plugins/ChangeLog.md
    - cp LICENSE Plugins/LICENSE.txt
    - cp Documentation.pdf Plugins/Documentation.pdf
    - mv Plugins Camomile
    - zip -r $release.zip Camomile
  - os: osx
    compiler: clang++
    env: release=CamomileMacOS
    script:
    - mkdir Dependencies/LibPd/build && mkdir Dependencies/LibPd/build/xcode/ && cd Dependencies/LibPd/build/xcode
    - cmake -GXcode ../..
    - cd ../../../..
    - xcodebuild -workspace Camomile.xcworkspace -scheme Camomile-libpd -configuration Release
    before_deploy:
    - rm Plugins/libCamomile.a
    - rm Plugins/libCamomileFx.a
    - rm Plugins/Examples/camomile.sh
    - cp README.md Plugins/README.md
    - cp ChangeLog.md Plugins/ChangeLog.md
    - cp LICENSE Plugins/LICENSE.txt
    - cp Documentation.pdf Plugins/Documentation.pdf
    - mv Plugins Camomile
    - zip -r $release.zip Camomile
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IaAt+xohgcO99ho2SEAPR2sGcC5w0KtzmGiarM02/VrY7ECu5JfeSsoohuxWSqI8K+Dnf0O/akIVbTcnXizigpK8cDH+tUC/0j9a/9MannlEhOXYAUjFsikWMEpiHQ5hqs84QTpwjzTMTPrYwxJft1GIChqJDUq2X+0++BPKwrTi+31V+1ZVQtZBF/ra80ivaigvC4ikm5FCFgWhemKdxiASi3s7pmTY68LYy7TvEJim4OHW7IUPJh9q1N2+TLfgrI8gP1lWkolU/dLSBjEZxsh/SEO1FO5lVNxoiGq/7urDVjoG6Bcow3JLWdw1k8WdjoIj5/ndUucgWzgd/6UoYbtnwnsHreg4EFE86NtkdELiP12bzk0B6rHJge+DHk3LYx0UH17a2y54WaiEuNCoDXlYlqARHzjz2KeglzldYnzoEEFi98ds68eyJVaFsnj0p3pvdujFtduPltbBfXyLVqNOJP+mjQyu7YvZiaev+mlCqYfZTM7B8eYowoP1K+jAsC4ulYWOaNqJWt/K+aFU+o7C1/wTkuSXhGV4wfCj5JvNwcsCt1XNiC29R6SAkThZk4D4+8hj5u+WQg4AUBdT2E3GVP+Fdg/C+bFRoKO2v9Yv7GBDxhfKwRrxRnSrUwmWEeZEWJwq3s2EMNXf0ycDiizzxJ3YxoPPkVUdSAQmVME=
  file: $release.zip
  on:
    repo: pierreguillot/Camomile
    tags: true
